services:
  controller:
    build:
      context: ./node_image
    image: tb3-ros2-node:jazzy
    container_name: tb3-controller-bridge
    networks:
      ros_net:
        ipv4_address: 172.18.0.10
    environment:
      ROS_DOMAIN_ID: 0
      RMW_IMPLEMENTATION: rmw_fastrtps_cpp
      FASTDDS_BUILTIN_TRANSPORTS: UDPv4
      ROS_SECURITY_ENABLE: ${ROS_SECURITY_ENABLE:-false}
      ROS_SECURITY_STRATEGY: Enforce
      ROS_SECURITY_KEYSTORE: /workspace/project/deployment/wsl_docker/keys
      ROS_SECURITY_ENCLAVE: /controller
    volumes:
      - ../../:/workspace/project:rw
    working_dir: /workspace/project
    stdin_open: true
    tty: true
    command: ["bash", "-lc", "sleep infinity"]

  attacker:
    build:
      context: ./node_image
    image: tb3-ros2-node:jazzy
    container_name: tb3-attacker-bridge
    depends_on:
      - controller
    networks:
      ros_net:
        ipv4_address: 172.18.0.50
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      ROS_DOMAIN_ID: 0
      RMW_IMPLEMENTATION: rmw_fastrtps_cpp
      FASTDDS_BUILTIN_TRANSPORTS: UDPv4
      ROS_SECURITY_ENABLE: ${ROS_SECURITY_ENABLE:-false}
      ROS_SECURITY_STRATEGY: Enforce
      ROS_SECURITY_KEYSTORE: /workspace/project/deployment/wsl_docker/keys
      ROS_SECURITY_ENCLAVE: /attacker
    volumes:
      - ../../:/workspace/project:rw
    working_dir: /workspace/project
    stdin_open: true
    tty: true
    command: ["bash", "-lc", "sleep infinity"]

networks:
  ros_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
