#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

sudo "$SCRIPT_DIR/secure_up.sh"
sudo env \
  CONTROLLER_PATTERN="${CONTROLLER_PATTERN:-forward}" \
  CONTROLLER_LINEAR_SPEED="${CONTROLLER_LINEAR_SPEED:-0.2}" \
  CONTROLLER_ANGULAR_SPEED="${CONTROLLER_ANGULAR_SPEED:-0.8}" \
  CONTROLLER_SQUARE_SIDE_SECONDS="${CONTROLLER_SQUARE_SIDE_SECONDS:-4.0}" \
  CONTROLLER_SQUARE_TURN_SECONDS="${CONTROLLER_SQUARE_TURN_SECONDS:-1.96}" \
  "$SCRIPT_DIR/run_controller.sh"
